version: '2'
services:
  web:
    container_name: odoo10_web
    image: odoo:10.0
    depends_on:
      - db
    links:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo10-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    container_name: odoo10_db
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo10-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo10-web-data:
  odoo10-db-data:
